In [1]:
import numpy as np
import pandas as pd
# صدا زدن کتابخانه ها

In [2]:
movies_df = pd.DataFrame(pd.read_csv('movies.csv'))
ratings_df = pd.DataFrame(pd.read_csv('ratings.csv'))
# خواندن فایل ها

In [3]:
movies_df.head()
# نشون دادن فایل فیلم ها

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
movies_df['year'] = movies_df['title'].str.extract(r'(\(\d+\))', expand = False)
movies_df['year'] = movies_df['year'].str.extract(r'(\d+)', expand = False)
# با این کد یک ویژگی جدید به اسم سال درست کردم که تاریخ رو نگه داره 

movies_df['title'] = movies_df['title'].replace(r'(\(\d+\))', '', regex = True).str.strip()
# اینجا هم اون زمان رو از اسم فیلم ها پاک کردم و با استریپ فاصله های اضافی رو حذف کردم

movies_df = movies_df[movies_df['genres'] != '(no genres listed)'].reset_index(drop = True)
# اون هایی که ندارن ژانر‌ رو حذف کردم 

movies_df['genres'] = movies_df['genres'].str.split('|')
# سبک هارو به لیست تبدیل کردم که بعد بتونم مولتی لیبل باینریزر کنم

In [5]:
movies_df.head()
# فایل فیلم هارو به صورت دیتا فریم نهایی نشون دادم

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995

In [6]:
from sklearn.preprocessing import MultiLabelBinarizer
# کتابخانه مورد نظر رو صدا زدم
mlb = MultiLabelBinarizer()
# این خط مثل کلاس ها میمونه که یک نمونه ساختم
genres_encoded = mlb.fit_transform(movies_df['genres'])
# اینجا یک لیست ساختم که بگه فیلم ها هرکدوم در هر سبک هستند یا نه
MoviesGenres = pd.DataFrame(genres_encoded, columns = mlb.classes_, index = movies_df.index)
#اینجا گفتم از چیزی که بالا ساختی با ستون های اسم سبک ها دیتا فریم بساز

In [7]:
MoviesGenres.head()
# اینجا هم نشون دادم که چجوری شد اون چیزی که برای سبک ها ساختم

,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [8]:
MoviesWithGenres = pd.concat([movies_df, MoviesGenres], axis = 1)
# اینجا هم اون چیزی که از سبک ها ساختم رو با اون فیلم ها وصل کردم بهم به صورت ستونی

In [9]:
MoviesWithGenres.head()
# اینجا هم باز نشون دادم چیزی که بالا هست

,movieId,title,genres,year,Action,Adventure,Animation,Children,Comedy,Crime,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,0,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men,"[Comedy, Romance]",1995,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II,[Comedy],1995,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
ratings_df = ratings_df.drop('timestamp', axis = 1)
# از امتیاز ها زمان ساخت رو استفاده نکردم

In [11]:
ratings_df.head()
# نشون دادم اون دیتا فریم امتیاز هارو

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [12]:
userInput = [
              {'title': 'Breakfast Club, The', 'rating': 5},
              {'title': 'Toy Story', 'rating': 3.5},
              {'title': 'Jumanji', 'rating': 2},
              {'title': 'Pulp Fiction', 'rating': 5},
              {'title': 'Akira', 'rating': 4.5}
           ]

inputMovies = pd.DataFrame(userInput)

# اینجا مثلا امیتاز های یک شخص هست

In [13]:
inputMovies.head()
# اینجا نشون دادم چیزی که بالا هست

                 title  rating
0  Breakfast Club, The     5.0
1            Toy Story     3.5
2              Jumanji     2.0
3         Pulp Fiction     5.0
4                Akira     4.5

In [14]:
inputId = MoviesWithGenres[MoviesWithGenres['title'].isin(inputMovies['title'].tolist())].reset_index(drop = True)
# اینجا از اون فیلم هایی که با سبکشون بود اونایی که کاربر بهش نمره داده رو جدا کردم

inputMovies = pd.merge(inputId, inputMovies)
inputMovies = inputMovies.drop(['genres', 'year', 'title', 'movieId'], axis = 1).reset_index(drop = True)
# اینجا هم بعضی از ویژگی هارو استفاده نکردم و قبلش باز وصل کردم دیتار فریم همراه با شماره فیلم و دیتارفریم فیلم هارو که دیتا فریمی از سبک ها و نمره داشته باشم

In [81]:
inputMovies.head()

,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,rating
0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,3.5
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2.0
2,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,5.0
3,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,4.5
4,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,5.0

In [16]:
userGenres = inputMovies.drop('rating', axis = 1)
# اینجا نمره هارو استفاده نکردم و یک دیتا فریم فقط با نوع فیلم هست

In [17]:
userGenres.head()

,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0
3,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [18]:
userProfile = userGenres.transpose().dot(inputMovies['rating'])
# ضرب ماتریسی واسه اینکه بفهمیم کدوم نوع فیلم هارو کاربر نمره چجوری داده

In [ ]:
userProfile

In [19]:
genresTable = MoviesWithGenres.set_index(MoviesWithGenres['movieId']).drop(['genres', 'year', 'title', 'movieId'], axis = 1)
# شماره فیلم رو در جای اون صفر یک دو و غیره گذاشتیم

In [20]:
genresTable.head()

,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [22]:
rec = ((genresTable * userProfile).sum(axis = 1)/(userProfile.sum()))
# اینجا هم ابنکه هر فیلم رو چقدر میپسنده کاربر مشخص کردم

In [23]:
rec = rec.sort_values(ascending = False)
# از زیاد به کم مرتب کردم

In [24]:
rec.head(10)

movieId
134853    0.734266
148775    0.685315
117646    0.678322
6902      0.678322
81132     0.671329
2987      0.664336
26340     0.657343
673       0.657343
1907      0.657343
51939     0.657343
dtype: float64

In [25]:
finally_rec = movies_df[movies_df['movieId'].isin(rec.head(10).index.tolist())].drop(['genres'], axis = 1).reset_index(drop = True)
#اینجا ده تا از فیلم هارو که در نهایت بیشترین شباهت رو داشتن رو از فیلم ها برداشتیم

In [26]:
finally_rec.head(10)

   movieId                                              title  year
0      673                                          Space Jam  1996
1     1907                                              Mulan  1998
2     2987                           Who Framed Roger Rabbit?  1988
3     6902                                      Interstate 60  2002
4    26340  Twelve Tasks of Asterix, The (Les douze travau...  1976
5    51939                TMNT (Teenage Mutant Ninja Turtles)  2007
6    81132                                             Rubber  2010
7   117646                     Dragonheart 2: A New Beginning  2000
8   134853                                         Inside Out  2015
9   148775                Wizards of Waverly Place: The Movie  2009